# Generated by Django 4.2.7 on 2023-11-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=10)),
                ('Last_name', models.CharField(max_length=10)),
                ('Username', models.EmailField(max_length=20)),
                ('Email', models.EmailField(max_length=20, unique=True)),
                ('Phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'customerdetails',
            },
        ),
    ]
