# Generated by Django 4.2.7 on 2023-11-02 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='Username',
        ),
    ]
