# Generated by Django 4.2.7 on 2023-11-02 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0002_remove_customer_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='BOOKDETAILS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=100)),
                ('Author', models.CharField(max_length=100)),
                ('Sellingprice', models.IntegerField(default=0)),
                ('Discountprice', models.IntegerField(default=0)),
                ('Discription', models.TextField(max_length=100)),
                ('Product', models.CharField(max_length=100)),
                ('Category', models.CharField(choices=[('NV', 'NOVELS'), ('PT', 'POETRY'), ('SR', 'STORY'), ('CD', 'CHILDRENS'), ('ST', 'SPIRITUAL'), ('MM', 'MEMORIES')], max_length=2)),
                ('Productimage', models.ImageField(upload_to='productimage')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('Email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoreapp.customer')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estoreapp.bookdetails')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
    ]
