# Generated by Django 4.2.7 on 2023-11-02 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estoreapp', '0003_bookdetails_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookdetails',
            name='Language',
            field=models.CharField(choices=[('EN', 'ENGLISH'), ('ML', 'MALAYALAM')], default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='bookdetails',
            name='Category',
            field=models.CharField(choices=[('NV', 'NOVELS'), ('PT', 'POETRY'), ('SR', 'STORY'), ('CD', 'CHILDRENS'), ('SC', 'SCIENCE'), ('AT', 'AUTOBIOGRAPHY')], max_length=2),
        ),
    ]
